apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hdc-ankalan

resources:
- ../../../base

labels:
  - pairs:
      app: ankalan-dr
    includeSelectors: true

patches:
- target:
    kind: Deployment
    name: appname
  patch: |-
    - op: replace
      path: /metadata/name
      value: ankalan-dr
- target:
    kind: Service
    name: appname
  patch: |-
    - op: replace
      path: /metadata/name
      value: ankalan-dr
