apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mndc-ankalan

resources:
- ../../../base

labels:
  - pairs:
      app: registrar-service
    includeSelectors: true

patches:
- target:
    kind: Deployment
    name: appname
  patch: |-
    - op: replace
      path: /metadata/name
      value: registrar-service
- target:
    kind: Service
    name: appname
  patch: |-
    - op: replace
      path: /metadata/name
      value: registrar-service
